### ISSUE TITLE
Split out SDK/APIs to a different package to conform to Hashicorp provider development guidelines

### ISSUE THREAD

**Issue by Prativa20** [vmware-archive/legacy-terraform-provider-vra7#107]
Move SDK to different package

**Comment by maelvls** [comment]
Having some [Terraform Acceptance tests](https://www.terraform.io/docs/extend/testing/acceptance-tests/index.html) would be a nice thing also as 95% of the current tests focus on testing the API 😀

**Comment by Prativa20** [comment]
Thanks @maelvalais for pointing this out. This is another requirement for the certification. I will open a separate issue for this.

**Comment by Prativa20** [comment]
Addressed this as part of #119
