### ISSUE TITLE
Providing lease days is not taking effect

### ISSUE THREAD

**Issue by Prativa20** [vmware-archive/legacy-terraform-provider-vra7#111]
**vRA 7.x version**
vRA 7.5
**Terraform version**
Terraform v0.11.7
The terraform-provider-vra7 plugin version (e.g. commit id, etc.)
**Describe the bug**
Providing lease_days inside catalog_configuration still creates a deployment with Indefinite lease.
**To Reproduce**
1. Provide this in your config file as in example 1 of README
catalog_configuration = {
         lease_days = "5"
     }
2. terraform apply
3. Check the deployment, the lease is still the default value, that is Indefinite

**Expected behavior**
Lease days should be 5 days

**Comment by Prativa20** [comment]
Correct parameter is _leaseDays and not lease_days.

**Comment by markpeek** [comment]
Fixed via #112
