### ISSUE TITLE
JSON requests are only made of strings, no integers or booleans

### ISSUE THREAD

**Issue by maelvls** [vmware-archive/legacy-terraform-provider-vra7#113]
For example, with the sample
```hcl
provider  "vra7" {
    username = "${var.username}"
    password  = "${var.password}"
    tenant = "${var.tenant}"
    host = "${var.host}"
}

resource "vra7_resource" "machine" {
  count            = 1
  catalog_name = "CentOS 7.0 x64"
  resource_configuration = {
    Linux.cpu = "2"
  }
}
```

Internally, Terraform parses the `Linux.cpu` as a string, as specified by the last `schema.TypeString` in

https://github.com/vmware/terraform-provider-vra7/blob/c56915cd5b41ad8b37a6eb77e710ecb2fcdf65f4/vrealize/schema.go#L257-L266

These right-value strings stay as is until the JSON serialization:

https://github.com/vmware/terraform-provider-vra7/blob/c56915cd5b41ad8b37a6eb77e710ecb2fcdf65f4/vrealize/resource.go#L605-L611

At this point, the JSON request `jsonBody ` will be something like

```json
{
  "type": "com.vmware.vcac.catalog.domain.request.CatalogItemProvisioningRequest",
  "catalogItemId": "e5dd4fba-45ed-4943-b1fc-7f96239286be",
  "requestedFor": "jason@corp.local",
  "businessGroupId": "53619006-56bb-4788-9723-9eab79752cc1",
  "description": null,
  "reasons": null,
  "data": {
    "Linux": {
      "data": { "cpu": "2" }
    }
  }
}
```

(cf. examples page 51 from the [vra-75-programming-guide])

[vra-75-programming-guide]: https://vdc-download.vmware.com/vmwb-repository/dcr-public/3f9ab622-499d-4caf-801b-2a6c1f83a6d4/ba2d7e2c-3320-4dfb-9ef0-39588cadda2e/vrealize-automation-75-programming-guide.pdf

As you can see, `cpu` is a string, which does not match the expected type (I would expect `"cpu":2`). Same thing happens with booleans (arrays aren't working either afaik).

Am I understanding & using the provider correctly? My company has implemented its vRA7 instance using component-less XaaS blueprints; their blueprints expect correct types in `"data": {}`. For example, 
 in one of the blueprints, a field `lease` is expected to be an integer, e.g., `90`, but the JSON request contains `"lease": "90"` which is rejected by the workflow and thus gives an error.

I would be pleased to join the dev effort if that might help!  🙂

**Comment by Prativa20** [comment]
@maelvalais Thanks for bringing this up. Although we haven't seen any issue around this yet while provisioning from terraform, but this is a valid issue. Could you reproduce this error? If yes, please share the config. And sure, if you want, please go ahead and open a PR, else we can fix it as well :)

**Comment by maelvls** [comment]
Thank you for your attention! 🙂

I will try to reproduce and document the behaviour asap. In fact, we are planning on extend your project in order to take into account the many specific features of our vRA7 instance. From what I know of the specifications for the provider we want to have, we might have to "hard fork", meaning that it will be hard or impossible to propose pull-requests or to pull changes from upstream.

That said, my personal intent and goal is to stay "all on the same boat", sticking as close as possible to the vmware upstream project. I really want to contribute to your project and to be able to work all together 🙂Doing so, everybody will benefit from our work! 🎉

I'll keep you updated.

**Comment by maelvls** [comment]
Hi! 👋 
I must close the issue for now as I (kind of) abandonned this idea. I’ll try later 🙂

Thank you for your kindness and your work!!
