### ISSUE TITLE
VM ok in VRA but Terraform timeout without any "Complete" info

### ISSUE THREAD

**Issue by guizello** [vmware-archive/legacy-terraform-provider-vra7#115]
I'm sorry but i have the same issue #73  but updating the vra plugin did not solve the problem.
My VM is well available in the portal  but Terraform didn't return a "Complete" information and crash because of the configured timeout..

✔  15:46 ~ [ master | ✚ 1 ] $ terraform --version
Terraform v0.11.11
+ provider.vra7 (unversioned)

✔  15:46 ~/TerraformPluginProject/src/github.com/vmware/terraform-provider-vra7 [ master | ✔  ] $ git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working tree clean
✔  15:47 ~/TerraformPluginProject/src/github.com/vmware/terraform-provider-vra7 [ master | ✔  ] $ ll ~/TerraformPluginProject/bin/terraform-provider-vra7 
-rwxr-xr-x 1 guizello guizello 21478884 déc.  17 15:23 /home/guizello/TerraformPluginProject/bin/terraform-provider-vra7

**Comment by Prativa20** [comment]
@guizello Did the execution time out or it crashed? And when you say "Complete" info, what kind of info is missing?

**Comment by guizello** [comment]
The terraform apply timed out (because there is a Timeout configured) and crashed whereas the vm was created in vra. It seems that terraform couldn't get any info from vra about the status of the request. Whatever is the Timeout configured, it will crash at the end. If I put 60min, it will timed out and crash. 

⁣Guizello

**Comment by Prativa20** [comment]
@guizello Can you please attach the vra-terraform.log and crash.log?

**Comment by guizello** [comment]
Sorry for the late, i don't have any crash.log because it doesn't crash. It just timeout (i've configured 15min).
Here is the logs attached :
![log](https://user-images.githubusercontent.com/5029347/50447854-41da3880-091e-11e9-8ec1-e7edf6b44082.PNG)
![crash](https://user-images.githubusercontent.com/5029347/50447878-70581380-091e-11e9-9fe3-f08b55e67f3c.PNG)

**Comment by Prativa20** [comment]
@guizello Looks like this has nothing to do with the request time out. The timeout behavior is as expected. It times out if the status does not change to either SUCCESSFUL or FAILED. Rather, the request is invoked and there is a problem with it. It never goes to IN PROGRESS or SUCCESSFUL or FAILED state. It remains in the SUBMITTED STATE.

It is difficult to debug with just this part of the log why the request is stuck at the SUBMITTED stage. I would need the .tf file and the vra-terraform.log file as well. Also, can you please attach a screenshot of the UI as well.

**Comment by guizello** [comment]
Yes i agree. I just don't know why the status doesn't change.
Here are the attached files.
[main.tf.txt](https://github.com/vmware/terraform-provider-vra7/files/2720376/main.tf.txt)
[UI.txt](https://github.com/vmware/terraform-provider-vra7/files/2720377/UI.txt)
[vra_terraform.log.txt](https://github.com/vmware/terraform-provider-vra7/files/2720378/vra_terraform.log.txt)

**Comment by guizello** [comment]
Allright, my bad. Everything's fine now..
The reason of this was because my url host was not ok.
"https://xxxxxx/vcac" instead of "https://xxxxxx"
I didn't get the reason of "Resource view failed to load:  invalid character '<' looking for beginning of value" and why i didn't have a "in progress" action.
Maybe a host/url check or better information in the log would be great.
Sorry about that and thanks for your help,
Guillaume
