### ISSUE TITLE
Terraform vRA 7 plugin should be able to request multiple instances of a VM if that is specified in a Blueprint

### ISSUE THREAD

**Issue by dzilbermanvmw** [vmware-archive/legacy-terraform-provider-vra7#116]
**vRA 7.x version - 7.5.1 (Build: 10475468)**
The vRA 7.x version where is issue is found.
**Terraform version - v0.11.10 **
The terraform version
**terraform-provider-vra7 plugin version -provider.vra7 (unversioned) (locally built) **
The terraform-provider-vra7 plugin version (e.g. commit id, etc.)

**Describe the bug**
Many multi-VM blueprints have a range of instances for a VM to be provisioned in a blueprint (e.g. from min=1 to max=8 instances, for example in K8s cluster. While is is possible to change # of requested instances in vRA request form (see attached screenshot), Terraform does not appear to support this property - at least not with the syntax I have tried with.

**To Reproduce**
1. Terraform config file - attached, attempting to request **Node._number_of_instances = 4**
2. Terraform command - terraform apply
3. Error  - there is an initial error displayed:
'Error: Error applying plan:
1 error(s) occurred:
* vra7_resource.Daniel_test_K8s_TF_deployment: 1 error(s) occurred:
* vra7_resource.Daniel_test_K8s_TF_deployment: Resource creation has timed out
Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.'

However, it doesn't impact the request as it has been submitted at that point and is in progress.

**Expected behavior**

**Screenshots**

**Logs**
Attach logs to help debug the issue
1. Attach vra-terraform.log
2. Attach Terraform console log (Enable terraform logs following the steps mentioned in https://www.terraform.io/docs/configuration/environment-variables.html)
3. crash.log(if any)

**Desktop (please complete the following information):**
 Windows 10 [Enterprise]()

**Additional context**

**Comment by dzilbermanvmw** [comment]
![k8s_master_nodes_request_form](https://user-images.githubusercontent.com/42846514/50258658-7fd2dc00-03b5-11e9-8e2e-fa3668569ed7.jpg)
[vra-terraform.log](https://github.com/vmware/terraform-provider-vra7/files/2697098/vra-terraform.log)

[k8s-calico-cava - Copy.tf.txt](https://github.com/vmware/terraform-provider-vra7/files/2697099/k8s-calico-cava.-.Copy.tf.txt)

**Comment by hobovirtual** [comment]
Hi @dzilbermanvmw 

The property name for number of instances is

`Node._cluster = 4`

Try this and let me know if it works.
Thanks!

**Comment by dzilbermanvmw** [comment]
### Thanks @hobovirtual - looks like this suggestion worked, just wonder where did that property '_cluster' came from? The attached version of the TF did initialize proper request with 4 'Node' VMs, the terraform show reflects that in status:

C:\DEV\terraform_ws>terraform show
vra7_resource.Daniel_test_K8s_cluster_deployment:
  id = 1961573f-d089-4d4c-8496-c1550151d540
  catalog_configuration.% = 2
  catalog_configuration._leaseDays = 20
  catalog_configuration._number_of_instances = 1
  catalog_id = 26ae1da3-a94d-4cde-b979-fc48206ddb7a
  catalog_name = Kubernetes with Calico networking
  deployment_configuration.% = 2
  deployment_configuration.description = Daniel's 4th Terraform Deployment - K8s cluster
  deployment_configuration.reasons = Testing the vRA 7 Terraform plugin on Cava for 1+4 VMs blueprint!
  request_status = IN_PROGRESS
  resource_configuration.% = 3
  resource_configuration.Master.cava_user_email_address = dzilberman@vmware.com
  resource_configuration.Master.k8s_yum_packages = docker kubeadm-1.13.0 kubelet-1.13.0 kubectl-1.13.0
  resource_configuration.Node._cluster = 4
  wait_timeout = 5
---------------------------------------------------------------------------------------------------
[k8s-calico-cava.tf.txt](https://github.com/vmware/terraform-provider-vra7/files/2700368/k8s-calico-cava.tf.txt)

 I can close this issue after verifying for another Blueprint with multiple VM instances.

**Comment by dzilbermanvmw** [comment]
I have also tested with another vRA 7 Blueprint containing multiple Nodes - vROPS cluster, see TF config file attached. I am not getting issues with Node count, but there is a blueprint level property 'gobuild_product_vrops_number' (not tied to any VM but to BP/Depl
[vrops-multivm-cava.tf.txt](https://github.com/vmware/terraform-provider-vra7/files/2703994/vrops-multivm-cava.tf.txt)
oyment as a whole) that I tried to enter in the  'catalog_configuration' section
-----------------------------------------------------------------------------------------------------------------
* vra7_resource.Daniel_test_vROS_Cluster_deployment: Resource Machine Request Failed: vRealize API: [{Code:20117 Message:The data specified within the request is invalid. SystemMessage:The data specified within the request is invalid.} {Code:11001 Message:The 'gobuild_product_vrops_number' field is required. SystemMessage:Field with id gobuild_product_vrops_number is required.}]

**Comment by dzilbermanvmw** [comment]
Closing the PR with a caveat that the usage of "_cluster" property is documented somewhere. Working with our Developer @Prativa20 on the Deployment level property support issue above. Happy Holidays :)

**Comment by Prativa20** [comment]
> gobuild_product_vrops_number

Hi @dzilbermanvmw 

Putting the custom deployment level property under catalog_configuration will solve this issue. So, any deployment level properties will always go under catalog_configuration and deployment_configuration will strictly have only "reason" and "description". We will work towards documentation and design refinement. Thank you so much for the extensive testing.

catalog_configuration = {
    _leaseDays = "20"
    _number_of_instances = 1
    gobuild_product_vrops_number = ######
  }

Please let me know if it works.
