### ISSUE TITLE
Implement semver tags to allow for go module usage

### ISSUE THREAD

**Issue by d-luu** [vmware-archive/legacy-terraform-provider-vra7#117]
Can we get a semver tag on a release build? I am using this provider as part of a project that utilizes go modules but it require packages to be semantically versioned. I would like to avoid extra tooling if possible. Thanks

**Comment by markpeek** [comment]
@d-luu I'm assuming tagging the current top of master with "v0.0.1" would do what you wanted, correct? 

Please note that some breaking changes are likely coming with Issues such as #107. Out of curiosity, what interfaces are you using for your project?

**Comment by d-luu** [comment]
v0.0.1 would work fine

As for the changes coming in https://github.com/vmware/terraform-provider-vra7/issues/107, I will cross that bridge when the time comes.

For interfaces, I actually call the Terraform API (along with provider APIs) rather than using the CLI as I do some data verification amongst other things.

**Comment by markpeek** [comment]
Sorry for the delay. I just tagged v0.0.1 before we split out the sdk and other changes.
