### ISSUE TITLE
Proposal for some changes in the terraform config file to make it simpler and readable

### ISSUE THREAD

**Issue by Prativa20** [vmware-archive/legacy-terraform-provider-vra7#131]
Hi,

We have seen a lot of questions and confusions around how to write a terraform config file for the vra7 provider. The current structure is not very intuitive and also repetitive. I have a proposal to make some changes. Kindly provide your feedback from the sample below.

Proposed changes:
1. Rename the resource from vra7_resource to vra7_deployment
2. Provide the general properties of deployment like description and reasons at the resource level map instead of deployment_configuration.
3. Remove catalog_configuration.
4. Provide custom properties of deployment under deployment_configuration.
5. Not repeat the resource/machine names in resource_configuration properties by adding a map for a resource.
```
resource "vra7_deployment" "Deployment_1" {
  count = 1
  catalog_item_name = "Prativa_CentOs"
  description = "Prativa's deployment 1"
  reasons = "Testing the vRA 7 Terraform plugin"

  deployment_configuration = {
    _leaseDays = "5"
   _number_of_instances = 1
  }

  resource_configuration = {
    machine1 = {
      cpu = 1
      memory = 1024
      location.loc = "Palo Alto 1"
    }
    machine2 = {
      cpu = 2
      memory = 2048
    }
  }
  wait_timeout = 5
  businessgroup_name = "Dev"
}
```

@markpeek @dmettem @hobovirtual @VincenzoDo @mponton @nferro @jasonlivie @d-luu

**Comment by nferro** [comment]
Looks good, as this would be a breaking change my suggestion is to keep the old `vra7_resource` around as deprecated so it won't break previous deployments.

**Comment by mponton** [comment]
@Prativa20 I definitely prefer the new  `resource_configuration` syntax. Having to repeat the resource name is a bit redundant. I agree with the other changes as well (I see how they better match the template schema). I see @nferro 's point but I feel trying to keep things working both ways may make the code harder to maintain. However I'll be very honest, I am not objective since we don't enough investment yet to care much about this. Maybe a middle ground would be to include a small tool/script to convert existing TF files from old to new format? Unless you feel you can support both syntaxes in the plugin without too much gymnastics :smile:

**Comment by hobovirtual** [comment]
Hi @Prativa20 

I definitely feel the proposed structure is more adequate and make it easier to consume/define. Removes a lot of redundant definition.

I also feel the same as @mponton for the backward compatibility. I understand @nferro points as well.

Looking forward!

**Comment by bill-rich** [comment]
Looks like a good plan @Prativa20. Why the leading underscores though in `_leaseDays` and `_number_of_instances`?

**Comment by Prativa20** [comment]
@bill-rich These attribute names are mapped to the fields in the API, so, this is what the vRA API expects them to be.

**Comment by bill-rich** [comment]
I'll check into if there is an official stance on it, but I think dropping the leading underscore would fit better in the Terraform naming scheme even if it doesn't exactly match what will be used for the API.

**Comment by Prativa20** [comment]
The proposed changes has been implemented except 5 (check the description of this issue for detail). Current version of terraform does not support map of maps in their resource schema. Once it will be supported, we will make the changes for 5. 

Closing the issue
