### ISSUE TITLE
Provider tracks request as opposed to infrastructure in tfstate

### ISSUE THREAD

**Issue by grantorchard** [vmware-archive/legacy-terraform-provider-vra7#14]
I'm not certain whether this is by design or not, but tracking the request rather than the output of the request (ie the infrastructure components) makes it impossible to interpolate values between resources in a given definition. It also means I can't capture infrastructure properties (such as IP address, hostname) and instead need to login to the vRA portal to get this information.

This behaviour is contrary to every other tf provider that I have used.

**Comment by virajindasrao** [comment]
Hi @grantorchard ,
This feature is initiated in PR #20 . Getting out IP will be a good option and helpful from user view.

**Comment by Marcvd316** [comment]
Hi @virajindasrao, 

I think what @grantorchard means is that the tfstate file should reflect the actual state of the machine in vRA, not just the result of the vRA request that was made for its initial creation. For example, if you create a resource in a Terraform configuration that creates a VM that has 2 disks, and later on someone adds 2 more disks to that VM, Terraform will never know about the 3rd and 4th disks. All it knows is that initially the deployment was created with 2.

Running a "terraform refresh" should update the tfstate file and running a terraform plan should warn the user of the differences between the configuration file and the actual state of the VM.

**Comment by virajindasrao** [comment]
Hi @Marcvd316,
 I am planning to start work on the same. I will keep you guys updated on the same.

**Comment by virajindasrao** [comment]
[Pull Request](https://github.com/vmware/terraform-provider-vra7/pull/27) created.

**Comment by virajindasrao** [comment]
#27 Merged.
