### ISSUE TITLE
Provider Review

### ISSUE THREAD

**Issue by bill-rich** [vmware-archive/legacy-terraform-provider-vra7#147]
Hello! 

I’ve taken a look at the provider here and would like to say great work so far! I do have feedback outlined below that I’d like to see addressed before we move on to the next steps. I’m opening this issues as a sort of checklist for tracking remaining items and discussion. The review was done on the git commit 083de474f15dabab18533d4623cabfd664aa172e.

- [x] The schema and resource for `vra7_deployment` should be in `resource_vra7_deployment.go` rather than `provider.go`. The function naming is a little confusing too. `ResourceDeployment()` would probably be more clear than `ResourceMachine()` 

- [x] Attribute keys within the schema should not be read in from elsewhere. Making the Schema not embedded in the Resource is a bit non-standard, but ok. The setup should be simplified a bit though so it is easier to read and understand. See here for a good example.

- [ ] Use the `log` package, and each of the CRUD functions should include at least two log entries. One for when the function begins and one for when it completes successfully.

- [x] All the attributes should be read and set on `Read` so that differences between the configuration and the actual state can be caught. Any non-scalar values (TypeList, TypeSet, TypeMap) should have errors checked when setting.

- [ ] It's not recommended setting anything other than Id in the update function. There are cases where it is required, but it should be generally left to the read function when possible.

- [ ] There are no required attributes in the schema. Is that accurate?

- [x] CHANGELOG.md is required. See here for more details.

- [x] Documentation is required before the provider can be published

- [x] Splitting the basic and update acceptance tests will help with troubleshooting if an error is encountered. 

- [x] The acceptance tests should also include `CheckDestroy` to ensure that the resources are being properly destroyed.

**Comment by Prativa20** [comment]
Thanks @bill-rich for the quick review.
Starting to make the changes soon.

**Comment by Prativa20** [comment]
Following are the PRs that addressed the review comments:
#148 
#149 
#151 
#152 
#153

**Comment by Prativa20** [comment]
Hi @bill-rich 
Regarding **"There are no required attributes in the schema. Is that accurate?"**

One of the attributes, catalog_item_name or catalog_item_id is required and not both of them. So, we have kept it optional

**Comment by bill-rich** [comment]
Things are looking great and I think we're almost there. I found a couple more small things.

- [x] The format on the version numbers in CHANGELOG.md is important as it is used in our build and release scripts. It should be like this `## 1.9.0 (October 31, 2018)` with no link for the version numbers, and the unreleased version should be this format: `## 1.10.1 (Unreleased)`

- [x] Documentation looks good, but is `website/docs/r/BasicSingleMachine.yaml` used or referenced somewhere?

On the couple of points that require followup:
1. I see where additional logging information can be quite useful, but using a different package could cause problems with logging integration with the rest of Terraform and other providers. Would it be possible to use both and enable the additional logging in the `op/go-logging` package when a certain environment variable is set?
2. If there are exceptions that need to be set in Read, that is ok. Just wanted to make sure it was necessary.
3. Its ok if there aren't required attributes. It looks like you've got a check in there to ensure one is set. That is a common way of handling that.

**Comment by Prativa20** [comment]
Hi @bill-rich website/docs/r/BasicSingleMachine.yaml is used in the documentation and there is a reference to this file in there.

**Comment by bill-rich** [comment]
Thanks for getting everything addressed! I believe the provider is ready to go. I'll let @cgriggs01 know.

**Comment by cgriggs01** [comment]
Hey @Prativa20,

Congrats on finishing up the review. There are just one more this we need to address. All official Terraform providers use a [MPL2](https://github.com/terraform-providers/terraform-provider-vcd/blob/master/LICENSE) License, would you be able to change the license from `MIT` --> `MPL2`

Thanks Chris!

**Comment by markpeek** [comment]
Closing due to move from VMware org to terraform-providers org.
