### ISSUE TITLE
Invalid component name when using XaaS blueprint

### ISSUE THREAD

**Issue by jripault** [vmware-archive/legacy-terraform-provider-vra7#150]
**vRA 7.x version**
7.5
**Terraform version**
0.11.3
**terraform-provider-vra7 plugin version**
0.1.0

**Describe the bug**
I have a XaaS Blueprint using a simple form.
The request template is this :
```
{
  "type": "com.vmware.vcac.catalog.domain.request.CatalogItemProvisioningRequest",
  "catalogItemId": "xxxx",
  "requestedFor": "xxxx",
  "businessGroupId": "xxxx",
  "description": null,
  "reasons": null,
  "data": {
    "DestinationNames": null,
    "ISMPnumber": null,
    "SourceNames": null,
    "destinationIP": null,
    "destinationType": null,
    "forceOpeningToEdges": null,
    "isUniversalDestination": null,
    "isUniversalSource": null,
    "servicesNames": null,
    "sourceIP": null,
    "sourceType": null
  }
}
```

In TF file, I define the resource like this:

```
resource "vra7_deployment" "application_database"{
  catalog_item_name = "Create a Firewall Rule"
  resource_configuration = {
    sourceType = "SECURITYGROUP"
    SourceNames = "DEMO_APPLICATION"
    destinationType ="SECURITYGROUP"
    DestinationNames="DEMO_DATABASE"
    servicesNames = "TCP_3306"
  }

  reasons = "DEMO "
  description = "DEMO Middle/Back"
}
```

when terraform apply, I get the error :
`The resource_configuration in the config file has invalid component name(s): servicesNames, destinationType, DestinationNames, SourceNames, sourceType `

I checked the code and indeed, it seems not to be managed like this in resource_vra7_deployment.go as there is no handling of that kind of blueprint as there is no component in it

I was wondering if I am doing something wrong or if it is not supported yet. Should I work on new resource for this ?

**Expected behavior**
vRA API call correctly done

**Comment by Idanatcox** [comment]
we experience the same issue, did you manage to get around this?

**Comment by jripault** [comment]
Not yet. I tried modifying the provider but no success right now. I'll do a PR if successful

**Comment by javansickle** [comment]
We had a similar issue but got past it by moving the XaaS properties from the **resource_configuration** section to the **deployment_configuration** section.

**Comment by jripault** [comment]
Indeed it works with deployment_configuration
Thx
