### ISSUE TITLE
Need to relicense from MIT to MPL2

### ISSUE THREAD

**Issue by markpeek** [vmware-archive/legacy-terraform-provider-vra7#156]
As part of the HashiCorp certification and moving this code into the terraform-providers organization, the license for this code needs to be changed from the current [MIT](https://github.com/vmware/terraform-provider-vra7/blob/master/LICENSE.txt) to [Mozilla Public License 2.0](https://github.com/hashicorp/terraform/blob/master/LICENSE) similar to that in terraform and providers.

To move forward, we need approval from some committers to this repo. Could the following committers respond to this issue with their approval?

@cars 
@dusty73 
@MichaelPak 
@nferro 
@sky-philipalmeida 

Thank you!

**Comment by cars** [comment]
I approve....

**Comment by nferro** [comment]
Approved

**Comment by sky-philipalmeida** [comment]
@markpeek sorry but I disapprove. 
My contribution was only 1 commit and only documentation so I think you will be fine removing that.

**Comment by markpeek** [comment]
@sky-philipalmeida commit has been reverted via 03ac9620eb254204f4086b432fac19b9ddf8f93c

**Comment by MichaelPak** [comment]
Approved

**Comment by markpeek** [comment]
Closed via #157
