### ISSUE TITLE
Doesn't work with Terraform version 0.12

### ISSUE THREAD

**Issue by diogoferreirasky** [vmware-archive/legacy-terraform-provider-vra7#161]
**Terraform version**
Terraform version 0.12

**Provider Version**
latest, commit: 50fbca71ae96b59a7885e98e8c4545c9c05cbd12

**Describe the bug**
Terraform Version 0.12 doesn't work with this provider.
"Error: Failed to instantiate provider "vra7" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]"

**To Reproduce**
1. Install terraform 0.12
2. Install this provider latest version
3. Run terraform init
4. Run terraform plan
5. Boom Error.

**Screenshots**
![tempsnip](https://user-images.githubusercontent.com/49756557/59200517-58084800-8b90-11e9-8855-dc020afd20ff.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by mcascone** [comment]
I opened the same issue on the other repo for this. I don't know which one is the current supported repo. https://github.com/terraform-providers/terraform-provider-vra7/issues/13

**Comment by markpeek** [comment]
Thank you for the issue. There is an active PR tracking the work as well:
terraform-providers/terraform-provider-vra7#17
