### ISSUE TITLE
Disk Add Redux

### ISSUE THREAD

**Issue by cars** [vmware-archive/legacy-terraform-provider-vra7#21]
Re  Issue #5  about adding disks. This looks to be in part because the provider handles values in the **catalog_configuration** block differently than the  **resource_configuration**. For the catalog_configuration it looks to simply add the values to the JSON its building.
[https://github.com/vmware/terraform-provider-vra7/blob/083b54e79ab4c84022eb3b36f1d528beb5768420/vrealize/resource.go#L206-L210](https://github.com/vmware/terraform-provider-vra7/blob/083b54e79ab4c84022eb3b36f1d528beb5768420/vrealize/resource.go#L206-L210)

Whereas on the **resource_configuration** block it looks to be trying to  only replace values that exist in the request template. 
[https://github.com/vmware/terraform-provider-vra7/blob/083b54e79ab4c84022eb3b36f1d528beb5768420/vrealize/resource.go#L232-L250](https://github.com/vmware/terraform-provider-vra7/blob/083b54e79ab4c84022eb3b36f1d528beb5768420/vrealize/resource.go#L232-L250)

I wonder if  it needs to be changed to also add any remaining custom properties that weren't replaced?

**Comment by virajindasrao** [comment]
@cars Let's make catalog_configuration flow same as resource_configuration.
I will create PR for that.

**Comment by virajindasrao** [comment]
#24 created

**Comment by Marcvd316** [comment]
Hi Viraj, I believe it should be the other way around. It should be as easy as possible to add custom properties to your deployment. I think catalog_configuration and resource_configuration should work the way catalog_configuration works today, simply add a custom property to the configuration file and it will be included in the deployment. That would be the equivalent behavior of what you can do through the GUI, adding custom properties at any level desired.
