### ISSUE TITLE
System exception.; HTTP/1.1 503 Service Unavailable

### ISSUE THREAD

**Issue by Boran** [vmware-archive/legacy-terraform-provider-vra7#34]
Hi,

Am testing with terrform v0.10.7  and vRA v7.3.0.
Terraform init+plan work and on apply after:
ra7_resource.example_machine1: Still creating... (30s elapsed)
it fails with 
 vra7_resource.example_machine1: instance got failed while creating. kindly check detail for more information

Looking at the vRA UI, Request, the details show "HTTP Error 503. The service is unavailable"

The VRA authentication is working, the catalogue name is ok.
Creation of VM via the vRA interface work fine, any idea what kind of service it is trying to call for that 503?

The main.tf is simple:
```
resource "vra7_resource" "example_machine1" {
  count = 1
  catalog_name = "vSphereLabIT"
  resource_configuration = {
    Linux.cpu = "1"
    vSphere__vCenter__Machine_1.Hostname="sb-feb02"
    vSphere__vCenter__Machine_1.VirtualMachine.Network0.Address="10.176.209.11"
  }
  catalog_configuration = {
    lease_days = "5"
  }
}
```

Running in Debug mode, the json request submitted is:
```2018-02-02T12:21:47.881+0100 [DEBUG] plugin.terraform-provider-vra7: 2018/02/02 12:21:47 JSON Request Info: {"type":"com.vmware.vcac.catalog.domain.request.CatalogItemProvisioningRequest","catalogItemId":"627fa419-1aea-49c6-b6e9-8516dd262dfd","requestedFor":"myuser@vsphere.local","businessGroupId":"b866b952-29b1-4d62-b078-1a4ab28b045e","description":"deployment via terraform from mylinux","reasons":"New VM via terraform","data":{"LabIT":{"classId":"Blueprint.Component.Declaration","componentId":null,"componentTypeId":"com.vmware.csp.component.cafe.composition","data":{"_hasChildren":false},"typeFilter":"vSphereLabIT*LabIT"},"_leaseDays":null,"_number_of_instances":1,"lease_days":"5","vSphere__vCenter__Machine_1":{"classId":"Blueprint.Component.Declaration","componentId":null,"componentTypeId":"com.vmware.csp.component.cafe.composition","data":{"Hostname":"sb-feb02","VirtualMachine.Network0.Address":"10.176.209.11","_allocation":{"classId":"Infrastructure.Compute.Machine.Allocation","componentId":null,"componentTypeId":"com.vmware.csp.iaas.blueprint.service","data":{"machines":null},"typeFilter":null},"_cluster":1,"_hasChildren":false,"cpu":1,"datacenter_location":null,"description":null,"disks":[{"classId":"Infrastructure.Compute.Machine.MachineDisk","componentId":null,"componentTypeId":"com.vmware.csp.iaas.blueprint.service","data":{"capacity":12,"custom_properties":null,"id":1499858648954,"initial_location":"","is_clone":true,"label":"Hard disk 1","storage_reservation_policy":"StorageReservationPolicy","userCreated":false,"volumeId":0},"typeFilter":null}],"display_location":false,"guest_customization_specification":"Linux LABIT","machine_prefix":null,"max_network_adapters":-1,"max_per_user":0,"max_volumes":60,"memory":1024,"nics":null,"os_arch":"x86_64","os_distribution":null,"os_type":"Linux","os_version":null,"property_groups":null,"reservation_policy":{"classId":"Infrastructure.Reservation.Policy.ComputeResource","componentId":null,"id":"ReservationPolicy1","label":"ReservationPolicy1"},"security_groups":[],"security_tags":[],"snapshot_name":null,"source_machine_external_snapshot":null,"source_machine_vmsnapshot":null,"storage":12},"typeFilter":"vSphereLabIT*vSphere__vCenter__Machine_1"}}}```

Running tcpdump did not show http requests going anywhere except the vra server.

**Comment by virajindasrao** [comment]
Hi @Boran,
Have you tried the same configuration request through vRA UI?

**Comment by Boran** [comment]
Well yes it did, but Er, when I try now, the UI fails too. Oops (sheepish grin) I have a Vra issue, will get back...

**Comment by Boran** [comment]
rebooting the Iaas fixed it.
