### ISSUE TITLE
Terraform 0.11.2 Crashes

### ISSUE THREAD

**Issue by match-garricklinn** [vmware-archive/legacy-terraform-provider-vra7#35]
Requested in an email thread, the crash dump generated after rebuilding the plugin with debugging code from https://github.com/vmware/terraform-provider-vra7/tree/markpeek-debug-createresource

* vra7_resource.da2opws998d1: 1 error(s) occurred:
* vra7_resource.da2opws998d1: unexpected EOF

https://gist.github.com/garrickmatch/292f890643a5a2d7b1346de585107b4d

**Comment by markpeek** [comment]
@garrickmatch thank you for the log file. If I'm reading it correctly, I believe changing within your resource configuration ```WIN2016-HOSTTXT``` to ```WIN2016.HOSTTXT``` (using a period instead of a dash) should work around the issue. Please confirm.

If that does not work, please share your main.tf with anonymized data.

**Comment by match-garricklinn** [comment]
Well I'll be dipped....yep, that did the trick.  Glad it was something simple, thanks for helping track that down.

**Comment by markpeek** [comment]
Glad to hear it is working now. I'll leave this issue open to drive a fix to not crash by adding better data verifications and give a better error message.

**Comment by markpeek** [comment]
@garrickmatch a fix has been merged to give an error (rather than a crash) if someone doesn't have the right delimiter Thank you for raising the issue with us.
