### ISSUE TITLE
Terraform Crash (v0.11.3) when reducing count.

### ISSUE THREAD

**Issue by Rudikza** [vmware-archive/legacy-terraform-provider-vra7#37]
Hello,

I am using the latest build of terraform-provider-vra7 (16/02/2018) and I am able to successfully provisions two servers using count = 2 but when I reduce the count to 1 I get a terraform crash and the second server is removed from the statefile which is worrying.

Main.tf: https://gist.github.com/Rudikza/e75e4dd12f55c9357a7c70871d300189
Crashlog: https://gist.github.com/Rudikza/ed902a8577da1685d2ec28572ef6570f

any ideas?

**Comment by markpeek** [comment]
Thank you for the issue and crashlog.

@virajindasrao the errDestroyAction return from GetDestroyActionTemplate() can return several different errors (nil, APIError, golang error). However, this [line](https://github.com/vmware/terraform-provider-vra7/blob/master/vrealize/resource.go#L449) assumes it is an APIError with the call to Error(). We need to check for nil and should include type assertions when looking for specific APIErrors.

**Comment by markpeek** [comment]
@Rudikza a fix has been merged. Please try your use case again and let us know. Thanks.

**Comment by Rudikza** [comment]
Thanks, it's fixed.
