### ISSUE TITLE
Panic: Unknown validation type: 6

### ISSUE THREAD

**Issue by surewecan** [vmware-archive/legacy-terraform-provider-vra7#49]
**Terraform version:** 0.11.7
**Environment:** Ubuntu 14.04.5 LTS
**Go version:** go version go1.10.1 linux/amd64

Terraform commands are failing in case of adding values to resource_configuration/catalog_configuration section with the following error:

`panic: Unknown validation type: 6`

link to the config file: https://github.com/surewecan/terraform/blob/master/main.tf
crash log: https://github.com/surewecan/terraform/blob/master/crash.log

After removing resource_configuration/catalog_configuration sections terraform works just fine.

**Comment by virajindasrao** [comment]
Kindly use 'dep ensure' before compiling the binary.
For more information kindly refer [issue#52](https://github.com/vmware/terraform-provider-vra7/issues/52)
