### ISSUE TITLE
Unclear how to add a disk to a VM during creation

### ISSUE THREAD

**Issue by Marcvd316** [vmware-archive/legacy-terraform-provider-vra7#5]
I played around with trying to add a disk to a new VM with the vra7 Terraform plugin, but can't figure out how to get it to work, even after comparing with what the "disks" map looks like in a pure REST API request. Can you provide guidance on how to do it?

For example, I've tried things like : 

  resource_configuration {
    vm.cpu                 = 4
    vm.memory              = 16384
    vm._cluster            = 2
    vm.disks.data.capacity = 50 -------------> Does nothing.
    vm.storage             = 50 -------------> Appears in the Request, but doesn't add a disk
  }

I also tried adding custom properties to the resource_configuration : 
VirtualMachine.DiskN.Size --> " More disks can be added by specifying VirtualMachine.Disk1.Size, 
 VirtualMachine.Disk2.Size and so on"

so I tried adding : 
vm.VirtualMachine.Disk0.Size = 51
vm.VirtualMachine.Disk1.Size = 51
vm.VirtualMachine.Disk2.Size = 51

Without succcess...

Thanks!

**Comment by Marcvd316** [comment]
After more trial & error, I found a way to add disks to a VM duringdeployment. The custom properties for "VirtualMachine.DiskN.Size" need to be applied in the "catalog_configuration" block (at the vRA Deployment level) which is then inherited by all the VMs in the request.

This is not an issue for my current use case, but it could be for people who have blueprints with different VM types in a single blueprint that need to have different disk layouts, because all of those different VMs will inherit the same configuration from the Deployment's custom properties. That is unless there would be a way to override the custom properties set in the catalog_configuration block, inside the resource_configuration block.

Anyway, the plugin looks promising so far, I'll continue to use it and report here if I find any more issues.
Thanks!

**Comment by cars** [comment]
@Marcvd316  - Do you have any examples of this you can share? I'm not seeing the same results. I'm so unable to add disks at all to my deployments... even trying to set the value in the catalog_configuration block doesn't work for me.

**Comment by Marcvd316** [comment]
Hi @cars ,

Here is an example of a TF config file that successfully added disks during provisioning : 

resource "vra7_resource" "VMwithDisk" {
		catalog_name = "Standard VM"
		catalog_configuration = {
			_deploymentName = "VM with Disk"
			VirtualMachine.Disk1.Size = 325
		}
		resource_configuration{
			CMZvm.cpu = 8
			CMZvm.memory = 16384
			CMZvm._cluster = 2
		}
	}
