### ISSUE TITLE
not java.lang.String for Field: datacenter_location

### ISSUE THREAD

**Issue by eolix** [vmware-archive/legacy-terraform-provider-vra7#51]
Terraform v0.11.7 / Terraform v0.11.0

Passing on the main.tf:

```
resource_configuration = {
    Machine.cpu = "2"
    Machine.memory = 2048
    Machine.datacenter_location = "UK-South-HHE-1"
    Machine.VirtualMachine.Disk1.Size = ${var.DISK_SIZE}
}
```

Gives the error:

> Error: Error applying plan:
> 
> 1 error(s) occurred:
> 
> * vra7_resource.vra7-plugin-test-01: 1 error(s) occurred:
> 
> * vra7_resource.vra7-plugin-test-01: Resource Machine Request Failed: vRealize API: [{Code:10101 Message:Invalid argument. SystemMessage:Expected EntityReferenceDatum, not java.lang.String for Field: datacenter_location}]
> 
> Terraform does not automatically rollback in the face of errors.
> Instead, your Terraform state file has been partially updated with
> any resources that successfully completed. Please address the error
> above and apply again to incrementally change your infrastructure.
> 
> 
> 
> Add CommentCollapse

**Comment by virajindasrao** [comment]
Let me try this out.

**Comment by hobovirtual** [comment]
It works on my case using the following declaration

resource "vra7_resource" "machine1" {
  count = 1
  catalog_name = "centOS 7 (x64)"
  wait_timeout = 30

  resource_configuration = {
    centOS7.datacenter_location = "New York Prod"
    machine1.cpu = 2
  }

  catalog_configuration = {
    reasons     = "Test"
    description = "deployment via terraform"
  }
}

CentOS7 being the virtual machine Id in the blueprint canvas

**Comment by virajindasrao** [comment]
Hi @eolix 
The error occurred because the design you are using has no ```custom property datacenter_location```
Kindly refer the following link for how to add custom properties to design
https://docs.vmware.com/en/vRealize-Automation/7.4/com.vmware.vra.prepare.use.doc/GUID-B095B4DB-F2BB-4B87-A1B9-20173EDD28A8.html
