### ISSUE TITLE
Terraform destroy runs async (completes immediately)

### ISSUE THREAD

**Issue by DanielVaknin** [vmware-archive/legacy-terraform-provider-vra7#53]
Hi,

Not sure if that is by design or not, but currently, if running terraform destroy (or decreasing the count of a resource inside the main.tf file and running terraform apply), the destroy action completes immediately (and also outputs the requestId of the creation of the resources) while the vRA is still running the request of deleting the resources,
This is as opposed to the creation of resources, where terraform "waits" until the request is actually finished in vRA and outputs the request ID (which is a good behavior).

Expected:
- When destroying resources, terraform will query the vRA and wait until the destroy task has been finished,
- Once finished, terraform will display the request ID of the DESTROY request, and not the request ID of the CREATE request.

Thanks!

**Comment by raghavav** [comment]
Destroy should behave the same way as create. This is a valid issue to file.

We do have to check to see if there is a vRA limitation here that makes it hard to track the state of the resource when it is being destroyed. We'll investigate as part of this issue.
