### ISSUE TITLE
Documentation might be Incorrect

### ISSUE THREAD

**Issue by ALINRUISU** [vmware-archive/legacy-terraform-provider-vra7#61]
Based on the README.md 
|-/home/<USER>/TerraformPluginProject
    |-bin
    |-pkg
    |-pkg

should it not be the following structure?
|-/home/<USER>/TerraformPluginProject
    |-bin
    |-pkg
    |-src

**Comment by ALINRUISU** [comment]
changed source to src

**Comment by virajindasrao** [comment]
PR [#62](https://github.com/vmware/terraform-provider-vra7/pull/62) is out with fixes.
