### ISSUE TITLE
Documentation missing a step

### ISSUE THREAD

**Issue by g1ps** [vmware-archive/legacy-terraform-provider-vra7#67]
Hi,

your docs don't mention that you need to copy the plugin to `C:\Users\<user>\AppData\Roaming\terraform.d\plugins\windows_amd64.` on Windows. Failing to do that results in the new component not being seen by the system.

Cheers.

**Comment by virajindasrao** [comment]
It depends on the approach. You can place a plugin binary in the same directory where main.tf is placed.
But looking forward to your suggestion though.
I will update the document soon.
