### ISSUE TITLE
Terraform "depends_on" does not wait for the vRA request to be completed before moving on to next step

### ISSUE THREAD

**Issue by Marcvd316** [vmware-archive/legacy-terraform-provider-vra7#7]
When using the "depends_on" option in a "vra7_resource" block, it should ideally wait for its dependency to be completed with status "SUCCESFUL", however the observed behavior is that as soon as the dependency's request is made, it continues without waiting for it to be completed.

**Comment by virajindasrao** [comment]
[Pull request](https://github.com/vmware/terraform-provider-vra7/pull/10) created.

**Comment by markpeek** [comment]
Thanks! Fixed via #10.
