### ISSUE TITLE
Plugin does not support custom property values right now.

### ISSUE THREAD

**Issue by virajindasrao** [vmware-archive/legacy-terraform-provider-vra7#9]
The plugin does not support custom forms and other custom property values in the blueprint.

**Comment by Marcvd316** [comment]
Hi Viraj, just to clarify, I've successfully used the plugin to deploy XaaS blueprints and also using custom property values. However, I believe you are correct when you say "custom forms" AKA "dynamically populated custom properties" are not supported by the plugin. That seems to be a hurdle that needs to be worked around no matter how you use the vRA REST API (Terraform, Postman or other).

**Comment by grantorchard** [comment]
Can you provide an example definition for this? I am able to use custom properties without problem.
