### ISSUE TITLE
TERRAFORM CRASH

### ISSUE THREAD

**Issue by guizello** [vmware-archive/legacy-terraform-provider-vra7#95]
Hi,

Here are my specs:
> OS: CentOS 7.4
> terraform: v0.11.8
> go : 1.11.1

Terraform init is ok with the provider resource information.
Terraform plan is ok too when i try to add a "vra7_resource" block with the "catalog_id" parameter and its value into it.
If then i try to add an empty "catalog_configuration" bloc, plan is ok too.

But once i try to populate "catalog_configuration" (or another parameter, like resource_configuration) terraform crashes.

To recapitulate : 

**plan working**
>provider "vra7" {
>  username = "${lookup(var.infra_username, var.infra)}"
>  password = "${lookup(var.infra_password, var.infra)}"
>  host     = "${lookup(var.infra_host, var.infra)}"
>  tenant   = "vsphere.local"
>  insecure = true
>}
>resource "vra7_resource" "RHEL7" {
>  catalog_id = "${var.catalog_id}"
>  catalog_configuration = {
>  }
>} 

**plan not working**
>provider "vra7" {
>  username = "${lookup(var.infra_username, var.infra)}"
>  password = "${lookup(var.infra_password, var.infra)}"
>  host     = "${lookup(var.infra_host, var.infra)}"
>  tenant   = "vsphere.local"
>  insecure = true
>}
>resource "vra7_resource" "RHEL7" {
>  catalog_id = "${var.catalog_id}"
>  catalog_configuration = {
>    lease_days = 1
>  }
>} 

Someone have an idea and could help on this ? I attached the crash.log terraform gave.
Thanks very much,
Guillaume

[log.txt](https://github.com/vmware/terraform-provider-vra7/files/2473073/log.txt)

**Comment by Prativa20** [comment]
@guizello This looks like #52. Can you please make sure you are following all the steps mentioned in #52 and see if that fixes this issue?

**Comment by guizello** [comment]
Hello, 

I'm pretty sure that I did, but I'm gonna try to do it again. 
I Just won't be able to do it after the next 15 days. 
I'll let you know, thanks again 

Guillaume

**Comment by guizello** [comment]
Hello again, i've installed last 1.11 go version, relaunched dep ensure and rebuilt plugin.
Everything's fine indeed now. Sorry for that.
Thanks for your help !
